### ISSUE TITLE
Timeout error

### ISSUE THREAD

**Issue by jlcases** [amadad/agentcy#5]
I always have this problem when running this repo with a valid API key , GPT 3.5 16k 

```

File "/Users/jlcases/codigo/agentcy/venv/lib/python3.10/site-packages/openai/api_requestor.py", line 617, in request_raw
    raise error.Timeout("Request timed out: {}".format(e)) from e
openai.error.Timeout: Request timed out: HTTPSConnectionPool(host='api.openai.com', port=443): Read timed out. (read timeout=60)
```

I reviewed the code and timeout is set at 600s

Any thought?

**Comment by amadad** [comment]
Can you double-check your internet connection? Sometimes it's just that the connection gets unstable and can't hang on for the whole request. Also, might be worth a look to see if somewhere else in your setup there's a shorter timeout sneaking in, because it looks like the timeout setting isn't sticking like you thought.
